# Setup
title:               Taeho Je
tagline:             'Resume & Blog'
description:         '컴퓨터공학과 다니는 학생의 블로그입니다.'
url:                 https://stpcoder.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taeho Je
  url:               https://www.linkedin.com/in/TaehoJe
  email:             thbrian@postech.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
kramdown:
  parse_block_html: true
